/**
 * vizen_calendar 2012. 02. 01 
 * version 0.1 
 * by zpzgzerg (zpzgzerg@naver.com)
 */

	// 달력 인터페이스 생성
	function drawCalendar(id, startday, endday) {
		
		var contents = "";
		
		$(document.body).append("<div id='"+id+"'><div>");
		
		contents += "<table width='481' border='0' cellspacing='0' cellpadding='0'>";
		contents += "	<tr>";
		contents += "		<td height='59' style='background: url(img/calendar_topbg.gif) repeat-x left top' align='center'>";
		contents += "			<table width='462' height='39' cellpadding='0' cellspacing='0' border='0' class='calTOP'>";
		contents += "				<tr>";
		contents += "					<td class='year' valign='bottom'><input type='text' class='input' value='2012-02-01' style='width:70px'>";
		contents += "						부터";
		contents += "						<input type='text' class='input' value='2012-02-10' style='width:70px'>";
		contents += "						까지 &nbsp;<img src='img/calendar_hit_btn.gif' align='absmiddle'>";
		contents += "					</td>";
		contents += "					<td align='right' valign='top'><img src='img/calendar_btn_close.gif'></td>";
		contents += "				</tr>";
		contents += "			</table>";
		contents += "		</td>";
		contents += "	</tr>";
		contents += "	<tr>";
		contents += "		<td height='271' style='background: url(img/calendar_conbg.gif) repeat-x left top' valign='top'>";
		contents += " 			<table width='100%' cellpadding='0' cellspacing='0' border='0'>";
		contents += "				<tr>";
		contents += "					<td>";
		contents += "						<table width='100%' cellpadding='0' cellspacing='0' border='0'>";
		contents += "							<tr>";
		contents += "								<td width='23' valign='top' align='right'>";
		contents += "									<ul class='calMTul'>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "									</ul>";
		contents += "								</td>";
		contents += "								<td width='158' style='padding-top:20px;' valign='top'>";
		contents += "									<table width='100%' cellpadding='0' cellspacing='0' border='0'>";
		contents += "										<tr>";
		contents += "											<td width='18' valign='top' height='22'><img src='img/calendar_btn_back.gif'></td>";
		contents += "											<td valign='top' class='calyear' width='122'>2012년</td>";
		contents += "											<td width='18' valign='top'><img src='img/calendar_btn_next.gif'></td>";
		contents += "										</tr>";
		contents += "										<tr>";
		contents += "											<td colspan='3' height='2' bgcolor='#82868b'></td>";
		contents += "										</tr>";
		contents += "										<tr>";
		contents += "											<td colspan='3' valign='top'>";
		contents += "												<table width='100%' cellpadding='0' cellspacing='0' border='0' class='calYT'>";
		contents += "													<tr>";
		contents += "														<td class='Ycon'>";
		contents += "															<table width='125' cellpadding='0' cellspacing='0' border='0' class='calMT'>";
		contents += "																<tr>";
		contents += "																	<td class='Mcon'><a href='#'>1월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mbcon'><a href='#'>2월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>3월</a></td>";
		contents += "																</tr>";
		contents += "																<tr>";
		contents += "																	<td colspan='5' height='7'></td>";
		contents += "																</tr>";
		contents += "																<tr>";
		contents += "																	<td class='Mcon'><a href='#'>4월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>5월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>6월</a></td>";
		contents += "																</tr>";
		contents += "																<tr>";
		contents += "																	<td colspan='5' height='7'></td>";
		contents += "																</tr>";
		contents += "																<tr>";
		contents += "																	<td class='Mcon'><a href='#'>7월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>8월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>9월</a></td>";
		contents += "																</tr>";
		contents += "																<tr>";
		contents += "																	<td colspan='5' height='7'></td>";
		contents += "																</tr>";
		contents += "																<tr>";
		contents += "																	<td class='Mcon'><a href='#'>10월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>11월</a></td>";
		contents += "																	<td width='19'></td>";
		contents += "																	<td class='Mcon'><a href='#'>12월</a></td>";
		contents += "																</tr>";
		contents += "															</table>";
		contents += "														</td>";
		contents += "													</tr>";
		contents += "												</table>";
		contents += "											</td>";
		contents += "										</tr>";
		contents += "									</table>";
		contents += "								</td>";
		contents += "								<td width='38' valign='top' align='right'>";
		contents += "									<ul class='cdTableul'>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "										<li><a href='#'><img src='img/calendar_btn_choice.gif'></a></li>";
		contents += "									</ul>";
		contents += "								</td>";
		contents += "								<td width='262' style='padding-top:20px;' valign='top'>";
		contents += "									<table width='250' cellpadding='0' cellspacing='0' border='0'>";
		contents += "										<tr>";
		contents += "											<td width='18' valign='top' height='22'><img src='img/calendar_btn_back.gif'></td>";
		contents += "											<td valign='top' class='calyear' width='214'>2012년 2월</td>";
		contents += "											<td width='18' valign='top'><img src='img/calendar_btn_next.gif'></td>";
		contents += "										</tr>";
		contents += "										<tr>";
		contents += "											<td colspan='3' height='2' bgcolor='#82868b'></td>";
		contents += "										</tr>";
		contents += "										<tr>";
		contents += "											<td colspan='3' valign='top'>";
		contents += "												<table width='100%' border='0' cellspacing='0' cellpadding='0' class='cdTable'>";
		contents += "													<thead>";
		contents += "														<tr>";
		contents += "															<th scope='col'>일</th>";
		contents += "															<th scope='col'>월</th>";
		contents += "															<th scope='col'>화</th>";
		contents += "															<th scope='col'>수</th>";
		contents += "															<th scope='col'>목</th>";
		contents += "															<th scope='col'>금</th>";
		contents += "															<th scope='col'>토</th>";
		contents += "														</tr>";
		contents += "													</thead>";
		contents += "													<tbody>";
		contents += "														<tr>";
		contents += "															<td class='sun cd'><a href='#'>29</a></td>";
		contents += "															<td class='cd'>30</td>";
		contents += "															<td class='cd'>31</td>";
		contents += "															<td class='cdck'><a href='#'>1</a></td>";
		contents += "															<td class='cdck'>2</td>";
		contents += "															<td class='cdck'>3</td>";
		contents += "															<td class='cdck'>4</td>";
		contents += "														</tr>";
		contents += "														<tr>";
		contents += "															<td class='cdck'>5</td>";
		contents += "															<td class='cdck'>6</td>";
		contents += "															<td class='cdck'>7</td>";
		contents += "															<td class='cdck'>8</td>";
		contents += "															<td class='cdck'>9</td>";
		contents += "															<td class='cdck'>10</td>";
		contents += "															<td class='sat'>11</td>";
		contents += "														</tr>";
		contents += "														<tr>";
		contents += "															<td class='sun'>12</td>";
		contents += "															<td>13</td>";
		contents += "															<td>14</td>";
		contents += "															<td>15</td>";
		contents += "															<td>16</td>";
		contents += "															<td>17</td>";
		contents += "															<td class='sat'>18</td>";
		contents += "														</tr>";
		contents += "														<tr>";
		contents += "															<td class='sun'>19</td>";
		contents += "															<td>20</td>";
		contents += "															<td>21</td>";
		contents += "															<td>22</td>";
		contents += "															<td>23</td>";
		contents += "															<td>24</td>";
		contents += "															<td class='sat'>25</td>";
		contents += "														</tr>";
		contents += "														<tr>";
		contents += "															<td class='sun'>26</td>";
		contents += "															<td>27</td>";
		contents += "															<td>28</td>";
		contents += "															<td>29</td>";
		contents += "															<td class='cd'>1</td>";
		contents += "															<td class='cd'>2</td>";
		contents += "															<td class='sat cd'>3</td>";
		contents += "														</tr>";
		contents += "													</tbody>";
		contents += "												</table>";
		contents += "											</td>";
		contents += "										</tr>";
		contents += "									</table>";
		contents += "								</td>";
		contents += "							</tr>";
		contents += "						</table>";
		contents += "					</td>";
		contents += "				</tr>";
		contents += "				<tr>";
		contents += "					<td valign='top' align='right' style='padding:40px 12px 26px 0;'>";
		contents += "						<table width='277' cellpadding='0' cellspacing='0' border='0'>";
		contents += "							<tr>";
		contents += "								<td width='58'><img src='img/calendar_btn_today.gif'></td>";
		contents += "								<td width='58'><img src='img/calendar_btn_week.gif'></td>";
		contents += "								<td width='58'><img src='img/calendar_btn_month.gif'></td>";
		contents += "								<td width='58'><img src='img/calendar_btn_ninety.gif'></td>";
		contents += "								<td><img src='img/calendar_btn_hit.gif'></td>";
		contents += "							</tr>";
		contents += "						</table>";
		contents += "					</td>";
		contents += "				</tr>";
		contents += "			</table>";
		contents += "		</td>";
		contents += "	</tr>";
		contents += "</table>";
		
		$("#"+id).html(contents);
		
		
	}